[package]
name = "faith_router"
edition = "2024"
version = "1.0.0"
published-at = "0x1a4e54de06c9bfa76dfd8c2a4021e96309053ba2f871182d1757052fc4a25c44"

[dependencies]
# tide_core inherits its address from its own Move.toml
tide_core = { local = "../../core" }

[addresses]
faith_router = "0x1a4e54de06c9bfa76dfd8c2a4021e96309053ba2f871182d1757052fc4a25c44"
