[package]
name = "tide_core"
edition = "2024"
version = "1.0.0"
published-at = "0xe80798ff0e3f4fa1b51ebacd6e495f7765e3e073d7e49c153de57e0a77454843"

[dependencies]
# Sui, Bridge, MoveStdlib, and SuiSystem are implicitly imported (Sui 1.45+)

[addresses]
tide_core = "0x0"
