[package]
name = "tide_core"
edition = "2024"
version = "1.0.0"
published-at = "0xbf119a288b73ea42990f87a978c376d168b35439ce06c28d16fc8f5cfe2ebbae"

[dependencies]
# Sui, Bridge, MoveStdlib, and SuiSystem are implicitly imported (Sui 1.45+)

[addresses]
tide_core = "0xbf119a288b73ea42990f87a978c376d168b35439ce06c28d16fc8f5cfe2ebbae"
